#!/bin/bash
# REFAzeit V0.1
# Es ist zum Abstoppen von Ablaufabschnitten gedacht
# Die Zeit wird in Sekunden und nicht, wie üblich, in HM ausgegeben
# das soll in weiteren updates geschehen
# Ziel des Projektes ist eine Open Source Variante zu den kommerziellen
# Varianten zu bekommen

# Datei-Name vergeben
# Nach Starten läuft die Uhr
# Zum setzen des Messpunktes ENTER drücken
# Nun die Ablaufabschnitts-Nr. eingeben
# zum Schluss den Leistungsgrad vergeben (Eingabe von %)
clear
echo -n "Name der Zeitstudie: " && read za
echo -n Taste Drücken zum Starten && read x

start_time=$(date "+%s")

while read mp1; do
	echo -n "Ablaufabschnitt-Nr. "; read aa ; echo -n "Leistungsgrad in % "; read lg
	run_time=$(date +%s)
        delta_time=$((run_time - start_time))
    	echo -n $delta_time " Sekunden im Ablaufabschnitt: "$aa "LG = " $lg "%"
    	echo 
    	echo $delta_time $aa $lg >> ~/Studie_`echo -n $za`.txt
done
