#!/bin/bash
# REFAzeit V0.3b 16.09.2023
# Es ist zum Abstoppen von Ablaufabschnitten gedacht
# Die Zeit wird in Sekunden und nicht, wie üblich, in HM ausgegeben
# das soll in weiteren updates geschehen
# Ziel des Projektes ist eine Open Source Variante zu den kommerziellen
# Varianten zu bekommen

# Datei-Name vergeben
# Nach Starten läuft die Uhr
# Zum setzen des Messpunktes ENTER drücken
# Nun die Ablaufabschnitts-Nr. eingeben
# zum Schluss den Leistungsgrad vergeben (Eingabe von %)
clear
echo -n "Name der Zeitstudie: " && read za
echo -n Taste Drücken zum Starten && read x
echo "Zeit läuft. Drücke Enter für den ersten Messpunkt"

start_time=$(date "+%s")

while read mp1; do
	run_time=$(date +%s)
        delta_time=$((run_time - start_time))
        echo -n "Ablaufabschnitt-Nr. "; read aa ; echo -n "Leistungsgrad in % "; read lg ; echo -n "BZM "; read bm
        
        echo -n FZ: $delta_time " in HM im Ablaufabschnitt: "$aa "LG = " $lg "%   BZM:" $bm
    	echo 
    	echo
    	echo $delta_time $aa $lg $bm>> ~/Studie_`echo -n $za`.txt
	echo "Enter für Messpunkt"
done
